### ISSUE TITLE
flask.secret_key in the config example is still the secret key

### ISSUE THREAD

**Issue by guswynn** [jpwright/enmodal#15]
You seem to be rolling your own sessions, so this might not matter....

**Comment by jpwright** [comment]
thanks! the instance at app.enmodal.co is using a different key, but I edited the example to be more clear that you should generate your own.
https://github.com/jpwright/enmodal/commit/257d8d471a3e50254be6f67eb178b12e020ae668

**Comment by guswynn** [comment]
That's what I figured!
