### ISSUE TITLE
Stations not being named

### ISSUE THREAD

**Issue by Yuds2003** [jpwright/enmodal#19]
Whenever I make a station while using my enmodal server on the computer that the server is on, the it doesn't get named (I haven't tested it on other computers on the network).

**Comment by Yuds2003** [comment]
Update: I tested creating stations on an iPad and they didn't get names either.

**Comment by jpwright** [comment]
You'll need to have a valid reverse geocoding provider set up in your `settings.cfg`:
```
[geocode]
reverse_geocode_provider: mapbox
mapzen_key: MAPZEN_KEY
mapbox_key: MAPBOX_KEY
google_key: GOOGLE_KEY
```
Links to sign up for API keys are in the README. Both Mapbox and Google have free tiers that should cover a single user.
