### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by PisauraXTX** [jpwright/enmodal#21]
I encountered two issues while trying to install enmodal on my PC. They may be connected with one another, but I don't know enough about python etc. to be sure about that. 
1. Python never asked me whether I wanted to "Add Python to system PATH" during installation. Maybe there is another way to enable this after the installation, but I can't find it. 
2. The commands "pip", "virtualenv", and "venv\Scripts\activate.bat" do not work on my machine. Cmd doesn't know what to make of them. 
I'd be glad if anyone could help with these two problems. Thanks in advance.

**Comment by jpwright** [comment]
issue 2 is related to issue 1: if Python isn't in your system PATH, you won't be able to run those commands.

In the Windows installer it's a little tricky to find this option: go to "Customize" and make sure this feature is installed:
![image](https://user-images.githubusercontent.com/1292066/38568696-4750b94e-3cb7-11e8-996e-fb67cdebed42.png)

**Comment by PisauraXTX** [comment]
Thanks for your help. I realized I had been using a different installer for python which did not offer the relevant option. The .msi version worked for me, whereas the .exe did not.
