### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by redelleparole** [jpwright/enmodal#32]
Has anyone been able to install enmodal correctly? I'm getting stuck at the part about setting up the virtual environment. I set python as part of the system path but it still doesn't recognize pip and virtualenv as legitimate commands. Therefore, the virtual environment fails. In the end when I try to connect to the server, it says that the connection was reset and the website cannot be launched.

**Comment by Dezlite** [comment]
I'm stuck there as well, I have been trying to set this up for a long time now. If you have Python 2.7, it will not have PIP. The newer versions of Python have PIP bundled with it, so it can perform the PIP commands. There is a way to manually get pip installed, like downloading a file called `get-pip.py`, and then typing `python get-pip.py` in your terminal for PIP to be installed. I tried this and it failed. I also attempted using Python versions 2.7.9 and 3.9.1. These two versions have PIP bundled when you install it, but 2.7.9 gave an error that read `ERROR: Could not find a version that satisfies the requirement pip (from versions: none) ERROR: No matching distribution found for pip`. When I tried 3.9.1, I got to `pip install -r requirements.txt`, and then it gave me a huge error. 
Also one thing I noticed that when I tried getting PIP manually in version 2.7, it gave me a bunch of messages telling me that Python version 2.7 is losing support, and upgrading to Python 3.X is recommended. I'm assuming this is the reason why it is not working, but I do not know what to do at that point.

**Comment by jpwright** [comment]
Please use the most recent master with support for python3. When installing python3, make sure to check the "Add Python to system PATH" option.
I updated the instructions to use the "internal" pip and venv commands (`python -m pip`, `python -m venv`) so you do not need to worry about adding them to your system PATH, as long as python is there.
