### ISSUE TITLE
Issues with requirements.txt

### ISSUE THREAD

**Issue by DaMarMan111** [jpwright/enmodal#36]
Sorry to open an issue again but I seem to be having trouble. I'm not super experienced with code so that might be my issue lol. I tried running `pip install -r requirements.txt` but i keep getting this: `ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`. I checked the master folder and requirements.txt is there. Is it supposed to go somewhere else? This is also after i ran `python3 -m venv venv` instead of trying to install virtualenv as per the Mac instructions. Any help is appreciated, so sorry to bother you again.

**Comment by jpwright** [comment]
It sounds like you need to navigate to the `enmodal` folder in your Terminal before running the commands.

**Comment by DaMarMan111** [comment]
i used `cd enmodal` to navigate to enmodal and that is still coming up. could it be for any other reason?

**Comment by jpwright** [comment]
If the requirements.txt file exists in your working directory I see no reason why that message would appear, but perhaps it could be related to reinstalling python? You might also try `python3 -m pip install -r requirements.txt` to be sure you are using the newer version. The relevant pip docs are here: https://pip.pypa.io/en/stable/user_guide/#requirements-files

I will close this thread as it is not an issue with enmodal.
