### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by DaMarMan111** [jpwright/enmodal#37]
Sorry to open up yet another issue but I've finished all the steps required but I keep getting this error when trying to load localhost:5050.

<img src="https://imgur.com/rg512um.png">

**Comment by ajglonner** [comment]
Running grunt is not part of the steps given in the readme. Did you do that?

**Comment by DaMarMan111** [comment]
I installed grunt but I can't tell if it's running or not? Is it supposed to run automatically? Sorry I'm new at this lmao.

**Comment by ajglonner** [comment]
Use CMD to navigate to your enmodal folder and just type `grunt`

**Comment by DaMarMan111** [comment]
it finally worked !! turns out i hadn't installed grunt locally. thanks for the help !!
